### PR TITLE
Add start of prototype

### PR DESCRIPTION
**Pull request by skrawcz**
This is just me setting up a few things.

1. .gitignore 
2. setting up pre-commit hooks
3. adding discussion code.

### CODE REVIEW

**Comment by Roy-Kid** [comment]
That is wonderful! I ran the code and I think it is precisely what I want!

**Comment by skrawcz** [comment]
@Roy-Kid can we merge this then?

**Comment by Roy-Kid** [comment]
Sorry! I need to learn etiquette about when I should merge PR and start a new one. I am going to merge this PR and also promote your permission, in case I dont reply in time

**Comment by skrawcz** [comment]
> Sorry! I need to learn etiquette about when I should merge PR and start a new one. I am going to merge this PR and also promote your permission, in case I dont reply in time

yep we just need to align on ways of working! All good :)

**Pull request merged**
